### ISSUE TITLE
Tabs vs. spaces == sadness

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-sublime#202]
If one person has their editor set to use tabs and others use spaces, we get corruption sometimes.

**Comment by kans** [comment]
I think just warning people about this would be enough?  Otherwise, we'd need to detect tabs client side and transform spaces.

**Comment by ggreer** [comment]
I think just warning is fine. Not sure the best way to tell the user though. False positives could be really expensive.

**Comment by kans** [comment]
I think just tell the user when they join the workspace?  Clients tell the backend their tab settings when they join.  We warn the tab user if not everyone has tabs?  I suppose we'd need to watch the setting for updates, too...

**Comment by ggreer** [comment]
Colab now detects mixed indentation and sends warnings about this. We might need to tweak the warnings to make them more prominent, but the technical issue is fixed.
