### ISSUE TITLE
WiiU browser issue

### ISSUE THREAD

**Issue by Tcll** [Floobits/floobits-sublime#224]
figured I could code on my WiiU while I was away from my compys...
the workspace doesn't even display :(
it just loads up the title bar and stops at a white BG

using the WiiU is like connecting a USB KBd to your tablet while cloning the display to your TV.
it's really handy, though the numpad doesn't work... heh

it's also really good when not even your laptop is portable :P

**Comment by ggreer** [comment]
Sorry, but none of us at Floobits own a WiiU. Without some sort of error message, there's no way we can debug this.

**Comment by Tcll** [comment]
well, enabling developer mode, I don't get an error in the console...
I just can't see anything... I believe it's because of my `navigator.appVersion`, if you use that:

    "5.0 (Nintendo WiiU) AppleWebKit/536.30 (KHTML, like Gecko) NX/3.0.4.2.9 NintendoBrowser/4.2.0.11146.US"

need me to look for anything specific??
I'm not entirely new to web development :)
- all I really do is build plugins for my forum, but don't take that as anything small, I've built a UI for my custom smileys plugin with drag-n-drop support for example. ;)

**Comment by ggreer** [comment]
I'm pretty sure we're just using some JavaScript functionality that the WiiU doesn't support. This might be as simple as a one line change. The problem is finding that line.

You could try [enabling debug mode in your WiiU's browser](https://www.nintendo.com/wiiu/built-in-software/browser-specs/extended-functionality/), then connecting to it with Chrome. Be sure to append `?debug=1&loglevel=5` to your workspace URL. That will give you a lot more info about what's going wrong. You might even get source maps :).

And to answer your question: All communication with the back-end is done via a websocket. I'm pretty sure the WiiU supports websockets.

**Comment by Tcll** [comment]
> well, enabling developer mode, I don't get an error in the console...
debug mode, developer mode, whatever... lol

actually it's developer tools, but who cares, it's all for the same purpose...
blah blah :P

>Be sure to append ?debug=1&loglevel=5 to your workspace URL.
ah alright thanks, here's what I get from that: :)

Initing ext msg. build.web_editor.js:648
addfiles init 
Object
 build.web_editor.js:648
WebRTC: 
WebRTC
 build.web_editor.js:657
force updating PanelView of unknown because of Panels build.web_editor.js:648
configuring 
Object
 build.web_editor.js:648
3force updating PanelView of unknown because of Panels build.web_editor.js:648
connection connecting Tcll Universal-Model-Converter Tcll/Universal-Model-Converter build.web_editor.js:648
Connecting to https://floobits.com/ build.web_editor.js:648
discarding because event origin is 
Object
 build.web_editor.js:648
FlooHandler handler handling SIO_CONNECT undefined build.web_editor.js:648
connection auth Tcll/Universal-Model-Converter Universal-Model-Converter Tcll build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
Now authorized. build.web_editor.js:648
FlooHandler handler handling ROOM_INFO undefined build.web_editor.js:648
room info 
Object
 build.web_editor.js:648
my user id 15324 build.web_editor.js:648
force updating UserlistView of unknown because of Users build.web_editor.js:648
force updating FiletreeView of unknown because of tree build.web_editor.js:648
force updating undefined of unknown because of Messages build.web_editor.js:648
handling action onAction_messages_LOG build.web_editor.js:648
handling action onAction_messages_SUCCESS build.web_editor.js:648
setting mode to text build.web_editor.js:648
set 
Model
 . mode to text build.web_editor.js:648
setting mode to text build.web_editor.js:648
Configuring editor session build.web_editor.js:648
handling action onAction_editor_OPEN build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
handling action onAction_editor_OPEN_FROM_PATH build.web_editor.js:648
force updating undefined of unknown because of Messages build.web_editor.js:648
handling action onAction_messages_LOG build.web_editor.js:648
handling action onAction_handler_READY build.web_editor.js:648
handling action onAction_handler_BROADCAST_DATA_MESSAGE_FOR_PERM build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
force updating FiletreeView of unknown because of Permission build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
FlooHandler handler handling GET_BUF undefined build.web_editor.js:648
setting buf .floo build.web_editor.js:648
5handling action onAction_editor_CURSOR build.web_editor.js:648
FlooHandler handler handling ACK undefined build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
emit 
Object
 build.web_editor.js:648
emit 
Object
 build.web_editor.js:648

what should I expand?? >.>

btw, I'm getting the proper BG color now (no longer white)
but it's still completely blank with the menu-bar :P
lol

yea, I couldn't tell you what the WiiU browser actually supports... lol
(little info is provided when it comes to that)
I just know it supports a good portion of HTML5 and much more than the Wii browser... heh

and also... I think I was being stupid when I asked about the backend stuff...
I want to know a little more so I can know where I need to look to be of more help :)

**Comment by ggreer** [comment]
Yeah, the WiiU is deprecated completely now.
