### ISSUE TITLE
Does not prompt for directory when joining a new workspace

### ISSUE THREAD

**Issue by euwbah** [Floobits/floobits-sublime#235]
I get this error in the console when I turn on debug mode.
AttributeError: 'str' object has no attribute 'get'

Because I already have an old version of python installed (because of flootty), I'm not sure if this .get method of str is only available for the newer versions of python...

**Comment by ggreer** [comment]
What OS version, Python version, and Sublime Text version are you using? What is the traceback above the error?

**Comment by ggreer** [comment]
I'm betting that both of you put global settings in the auth section of your floorc.jsons.

I've tagged a new release (v3.5.7) that fixes this problem and logs if there are some suspicious settings in floorc.json.
