### ISSUE TITLE
 Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

### ISSUE THREAD

**Issue by markmark1** [Floobits/floobits-sublime#242]
Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548)

urgent not working pls let me know how to fix both in emacs and sublime and web-browser a

**Comment by ggreer** [comment]
This is fixed in the latest version of the plugin (v3.9.6).

**Comment by markmark1** [comment]
How to update to latest in emacs and sublime

________________________________

**Comment by markmark1** [comment]
upgraded still error

*Floobits SSL handshake error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:548)*

**Comment by plutonium-239** [comment]
@ggreer 
Even after the latest update with new certificates, I get the same error.
Is floobits going to be maintained?
