### ISSUE TITLE
Typing at the same time screws up the other person's cursor

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-sublime#59]
We fixed this in the web editor but it'll be really hard to get working in sublime. view.replace()  literally moves the user's cursor for a millisecond, so anything they type in that instant will go to the wrong place.

**Comment by A7ocin** [comment]
This doesn't seem to be fixed yet. Am I missing something?

**Comment by romcar** [comment]
No it still moves each pairs cursors around
